# Generated by Django 4.0.4 on 2022-07-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safeway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_price', models.IntegerField()),
                ('individual', models.BooleanField()),
                ('family', models.BooleanField()),
                ('premium', models.BooleanField()),
                ('hmo', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing',
                'verbose_name_plural': 'Pricings',
                'db_table': 'pricing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscription_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription_plan',
                'verbose_name_plural': 'Subscription_plans',
                'db_table': 'subscription_plan',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='notify',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ship_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordr_no', models.CharField(max_length=50)),
                ('itm_paid', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('Pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safeway.pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ship_Sub',
                'verbose_name_plural': 'Ship_Subs',
                'db_table': 'ship_sub',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pricing',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeway.subscription_plan'),
        ),
        migrations.CreateModel(
            name='Paid_Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sub_no', models.CharField(blank=True, max_length=36, null=True)),
                ('payment_code', models.CharField(max_length=50)),
                ('paid_item', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paid_Subscription',
                'verbose_name_plural': 'Paid_Subscriptions',
                'db_table': 'paid_subscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkout_Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordr_no', models.CharField(max_length=50)),
                ('itm_paid', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], max_length=50)),
                ('admin_remark', models.CharField(max_length=250)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safeway.pricing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout_Sub',
                'verbose_name_plural': 'Checkout_Subs',
                'db_table': 'checkout_sub',
                'managed': True,
            },
        ),
    ]
