# Generated by Django 4.0.4 on 2022-07-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='drug_type.jpg', null=True, upload_to='drug_type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drug_type',
                'verbose_name_plural': 'Drug_types',
                'db_table': 'drug_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Upload_Prescrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(upload_to='prescriptions')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload_Prescrip',
                'verbose_name_plural': 'Upload_Prescrips',
                'db_table': 'upload_prescrip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('product', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default='pharmacy.jpg', null=True, upload_to='pharmacy')),
                ('min_order', models.IntegerField(default=1)),
                ('max_order', models.IntegerField(default=5)),
                ('price', models.IntegerField()),
                ('malaria', models.BooleanField()),
                ('antibiotics', models.BooleanField()),
                ('c_f_c', models.BooleanField()),
                ('supplements', models.BooleanField()),
                ('overview', models.TextField()),
                ('effect', models.TextField()),
                ('ingredient', models.CharField(blank=True, max_length=300, null=True)),
                ('how_to_use', models.TextField()),
                ('advice', models.TextField()),
                ('display', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('drug_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.drug_type')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacys',
                'db_table': 'pharmacy',
                'managed': True,
            },
        ),
    ]
