# Generated by Django 4.0.4 on 2022-06-10 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, default='name', max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, default='name', max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_height', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='profile')),
                ('medication', models.BooleanField(blank=True, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('records', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'managed': True,
            },
        ),
    ]
